---
title: "ODD 02/2018 Retail Sales Data Analysis"
author: "Ahmet Turhal"
date: "Oct 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
- Downloading the row data
```{r}
library(tidyverse)
# Create a temporary file
tmp<-tempfile(fileext=".xlsx")
# Download file from repository to the temp file
download.file("https://github.com/MEF-BDA503/pj18-aturhal/blob/master/odd_retail_sales_2018_02.xlsx?raw=true",destfile=tmp, mode="wb")
# Read that excel file using readxl package's read_excel function. You might need to adjust the parameters (skip, col_names) according to your raw file's format.
raw_data<-readxl::read_excel(tmp,skip=7,col_names=FALSE)
# # Remove the temp file
file.remove(tmp)
```
- Civilize the data
```{r}
# Remove the last two rows because they are irrelevant (total and empty rows)
raw_data <- raw_data %>% slice(-c(43,44))

# Let's see our raw data
head(raw_data)

# Use the same column names in your data.
colnames(raw_data) <- c("brand_name","auto_dom","auto_imp","auto_total","comm_dom","comm_imp","comm_total","total_dom","total_imp","total_total")
# Now we replace NA values with 0 and label the time period with year and month, so when we merge the data we won't be confused.
car_data_feb_18 <- raw_data %>% mutate_if(is.numeric,funs(ifelse(is.na(.),0,.))) %>% mutate(year=2018,month=2)

print(car_data_feb_18,width=Inf)
```
- Save the data
```{r}
saveRDS(car_data_feb_18,file="~/Data Science/Big Data Essentials/odd_car_sales_data_feb_18.rds")
# You can read that file by readRDS and assigning to an object 
# e.g 
#rds_data <- readRDS("~/Data Science/Big Data Essentials/odd_car_sales_data_feb_18.rds")

```
- Analyze the data
```{r}
#List of total sales of brands that have sold more automobiles than commercial vehicles ordered in decreasing total sales
car_data_feb_18 %>%
  slice(-c(43,44)) %>%
  filter(auto_total > comm_total) %>%
  select(brand_name,auto_total, comm_total) %>%
  arrange(desc(auto_total))
```

```{r}
#List of total automobile sales of brands and their percentages to total respectively ordered in decreasing percentages 
car_data_feb_18 %>%
  slice(-c(43,44)) %>%
  transmute(brand_name, auto_total, auto_percents = round(auto_total/sum(auto_total)*100, 2)) %>%
  arrange(desc(auto_percents))
```
